version: '3.8'

services:
  test-service:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: flight-test-service
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped