apiVersion: v1
kind: ServiceMonitor
metadata:
  name: flight-search-metrics
  namespace: flight-search
  labels:
    app: flight-search
spec:
  selector:
    matchLabels:
      monitoring: "true"
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: flight-search-alerts
  namespace: flight-search
spec:
  groups:
  - name: flight-search.rules
    rules:
    - alert: HighErrorRate
      expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High error rate detected"
        description: "Error rate is {{ $value }} requests per second"
    
    - alert: HighLatency
      expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "High latency detected"
        description: "95th percentile latency is {{ $value }} seconds"
    
    - alert: VectorDBDown
      expr: up{job="vector-db"} == 0
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "Vector DB is down"
        description: "Vector database has been down for more than 2 minutes"